### ISSUE TITLE
Missing vgg16.pt

### ISSUE THREAD

**Issue by mohitm1994** [oneThousand1000/EG3D-projector#7]
I keep getting this error while running the code.
/HPS/EgofaceTrial/work/anaconda3/envs/eg3d/lib/python3.9/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Loading networks from "networks/ffhq512-128.pkl"...
Computing W midpoint and stddev using 600 samples...
Setting up PyTorch plugin "bias_act_plugin"... Done.
Traceback (most recent call last):
  File "/CT/TalkingHead/work/projector/eg3d/run_projector.py", line 150, in <module>
    run()  # pylint: disable=no-value-for-parameter
  File "/HPS/EgofaceTrial/work/anaconda3/envs/eg3d/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/HPS/EgofaceTrial/work/anaconda3/envs/eg3d/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/HPS/EgofaceTrial/work/anaconda3/envs/eg3d/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/HPS/EgofaceTrial/work/anaconda3/envs/eg3d/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/CT/TalkingHead/work/projector/eg3d/run_projector.py", line 132, in run
    w = w_projector.project(G, c, outdir,id_image, device=torch.device('cuda'), w_avg_samples=600,num_steps = num_steps,
  File "/CT/TalkingHead/work/projector/eg3d/projector/w_projector.py", line 94, in project
    with dnnlib.util.open_url(url) as f:
  File "/CT/TalkingHead/work/projector/eg3d/dnnlib/util.py", line 405, in open_url
    return url if return_filename else open(url, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './networks/vgg16.pt'

**Comment by oneThousand1000** [comment]
Hi, you can download vgg16.pt from https://nvlabs-fi-cdn.nvidia.com/stylegan2-ada-pytorch/pretrained/metrics/vgg16.pt and save it to `./network`. 

Or load it from url (vgg216.pt will be automatically downloaded): https://github.com/danielroich/PTI/blob/5f4c05726caa908a46537c5aaca6ebc8ea34201e/training/projectors/w_plus_projector.py#L64 , Line 64-66

**Comment by oneThousand1000** [comment]
Will update it in readme.

**Comment by mohitm1994** [comment]
Thanks a lot 👍
